apiVersion: apps/v1
kind: Deployment
metadata:
  name: echopod
  labels:
    app: echopod
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: echopod
  template:
    metadata:
      labels:
        app: echopod
    spec:
      containers:
      - name: echopod
        image: bschnorbus/echo-pod
        ports:
        - containerPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: echopod-service
spec:
  type: NodePort  # Change to LoadBalancer if using a cloud provider
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Port to expose on the node
  selector:
    app: echopod