apiVersion: networking.k8s.io/v1
kind: ingress
metadata:
  name: nginx-ingress
  namespace: nginx
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: nginx.internal.schnrbs.work
      http:
        paths: 
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80

